version: '4.24.0'

services:
#  zookeeper:
#    image: zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"


#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
