version: '4.24.0'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3.13.0-rc.2-management-alpine
    container_name: rabbitMQ
    ports:
      - "15672:15672"








